name: snakemakeEnv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake-minimal
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - numpy
